kind: pipeline
type: docker
name: backend

steps:
  - name: hello
    image: alpine
    commands:
      - echo Hello World!

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: hello
    image: alpine
    commands:
      - echo Hello World! Frontend

