kind: pipeline
type: docker
name: backend

steps:
  - name: hello
    image: alpine
    commands:
      - echo Hello World!

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: frontend

trigger:
  branch:
  - master

steps:
  - name: hello
    image: alpine
    commands:
      - echo Hello World! Frontend

