# Env Options
sudo: required
dist: trusty

# Language Options
language: go

go:
  - 1.9.7
  - 1.10.8
  - 1.11.10
  - 1.12.5
  - master
  - tip

before_install:
  - sudo apt-get update -qqy
  - sudo apt-get install -qqy upx golang-go

before_script:
  - go get -t ./...

script:
  - make travis-sizes
