# Env Options
sudo: required
dist: bionic

# Language Options
language: go

go:
  - 1.10.8
  - 1.11.12
  - 1.12.14
  - 1.13
  - 1.13.3
  - 1.13.4
  - 1.13.5
  - 1.13.6
  - master
  - tip

before_install:
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic universe" >> /etc/apt/sources.list
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic main restricted" >> /etc/apt/sources.list
  - sudo apt-get update -qqy
  - sudo apt-get install upx golang-go gccgo -qqy 
  - sudo apt-get autoremove -qqy

before_script:
  - gccgo -v
  - go get -t ./...
  - cd /usr/local/bin && sudo wget https://github.com/jondot/goweight/releases/download/v1.0.5/goweight_1.0.5_Linux_x86_64.tar.gz
  - cd /usr/local/bin && sudo tar -xf goweight_1.0.5_Linux_x86_64.tar.gz && sudo chmod 777 goweight

jobs:
  include:
    - stage: test-sizes
      script: make travis-sizes && make clean
    - stage: test-weight
      script: goweight
