# Env Options
sudo: required
dist: xenial

# Language Options
language: go

go:
  - 1.9.7
  - 1.10.8
  - 1.11.12
  - 1.12.11
  - 1.13
  - 1.13.3
  - master
  - tip

before_install:
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic universe" >> /etc/apt/sources.list
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic main restricted" >> /etc/apt/sources.list
  - sudo apt-get update -qqy
  - sudo apt-get install upx golang-go gccgo -qqy 
  - sudo apt-get autoremove -qqy

before_script:
  - gccgo -v
  - go get -t ./...

script:
  - make travis-sizes
