# Env Options
sudo: required
dist: bionic

# Language Options
language: go

go:
  - 1.10.8
  - 1.11.12
  - 1.12.14
  - 1.13
  - 1.13.3
  - 1.13.4
  - 1.13.5
  - 1.13.6
  - master
  - tip

before_install:
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic universe" >> /etc/apt/sources.list
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic main restricted" >> /etc/apt/sources.list
  - sudo apt-get update -qqy
  - sudo apt-get install upx golang-go gccgo -qqy 
  - sudo apt-get autoremove -qqy

before_script:
  - gccgo -v
  - go get -t ./...
  - go get github.com/jondot/goweight

jobs:
  include:
    - stage: test-sizes
      script: make travis-sizes
    - stage: test-weight
      script: goweight
