# Env Options
sudo: required
dist: trusty

# Language Options
language: go

go:
  - 1.8.5
  - 1.9.3
  - 1.9.4
  - "1.10"
  - "1.10.1"
  - master
  - tip

before_install:
  - sudo apt-get update -qqy
  - sudo apt-get install -qqy upx golang-go

script:
  - go get -t ./...
  - make travis-sizes
